# Generated by Django 4.1.13 on 2023-11-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoDBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('language_id', models.IntegerField()),
                ('original_language_id', models.IntegerField()),
                ('rental_duration', models.IntegerField()),
                ('rental_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.IntegerField()),
                ('replacement_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.CharField(max_length=20)),
                ('special_features', models.CharField(max_length=100)),
                ('last_update', models.CharField(max_length=50)),
                ('category_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
